baseurl      = "localhost"
title = "Quentin Dequippe"
subtitle = "Freelance Symfony Consultant"
keywords = "freelance, symfony, consultant"
languageCode = "fr-FR"
theme        = "hello-friend-ng"

paginate     = 10
rssLimit  = 10  # Maximum number of items in the RSS feed.

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
disableRSS     = false
disableSitemap = false
disable404     = false

defaultContentLanguage = "fr"

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[author]
    name = "Quentin Dequippe"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    # Subtitle for home
    homeSubtitle = "Geek // Freelance // Symfony Consultant"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true

    # Metadata mostly used in document's head
    description = "Quentin Dequippe's professional page and blog"
    keywords = "professional page, blog"
    images = [""]
    enableThemeToggle = true

#    enableGlobalLanguageMenu = true

    # Custom footer
    # If you want, you can easily override the default footer with your own content.
    #
    [params.footer]
        trademark = true
        rss = true
        copyright = true
        author = true

        topText = []
        bottomText = []

    [params.logo]
        logoMark     = " "
        logoText     = "<?php echo 'Hello World' ?> "
        logoHomeLink = "/"
        # Set true to remove the logo cursor entirely.
        logoCursorDisabled = true
        # Set to a valid CSS color to change the cursor in the logo.
#        logoCursorColor    = "#fff"
        # Set to a valid CSS time value to change the animation duration, "0s" to disable.
        # logoCursorAnimate  = "2s"

    # Social icons
    [[params.social]]
        name = "twitter"
        url  = "https://twitter.com/qdequippe"

    [[params.social]]
        name = "email"
        url  = "mailto:quentin@dequippe.tech"

    [[params.social]]
        name = "github"
        url  = "https://github.com/qdequippe"

    [[params.social]]
        name = "linkedin"
        url  = "https://www.linkedin.com/in/qdequippe"

    [[params.social]]
        name = "stackoverflow"
        url  = "https://stackoverflow.com/users/10353962/qdequippe"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

#[languages]
#    [languages.en]
#        title = "Quentin Dequippe"
#        subtitle = "Freelance Symfony Consultant"
#        keywords = "freelance, symfony, consultant"
#
#    [languages.fr]
#        title = "Quentin Dequippe"
#        subtitle = "Consultant Freelance Symfony"
#        keywords = "freelance, symfony, consultant"

[menu]
    [[menu.main]]
        identifier = "resume"
        name       = "Resume"
        url        = "https://dequippe.tech/resume/quentin_dequippe_resume.pdf"

    [[menu.main]]
        identifier = "posts"
        name       = "Blog"
        url        = "posts/"
